version: '3.7'
services:

  scoreboard:
    image: ghcr.io/carnach/crg-scoreboard:5.0.6
    container_name: scoreboard
    volumes:
      - ${PWD}/data/autosave/:/app/config/autosave/
    ports:
     - "8000:8000"
    restart: unless-stopped




  

